<a href="https://colab.research.google.com/github/ganeshmp01/DS-Classwork/blob/main/numpy_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***#numpy***

One dimensional array

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
type(a)
print("The number of dimension of a array is :", a.ndim)


[1 2 3]
The number of dimension of a array is : 1


Two dimensional array(x ,y)

In [ ]:
import numpy as np
B=np.array([
    [1,2,3],
    [4,5,6]
])
print(B)
print("The number of dimension of B array is :", B.ndim)
print("The shape of the matrix is " ,B.shape)


[[1 2 3]
 [4 5 6]]
The number of dimension of B array is : 2
The shape of the matrix is  (2, 3)


Three dimensional array : bunch of 2 dimensional array  (2X3X3)

In [ ]:
import numpy as np
c=np.array([
    [[1,2,3],
     [4,5,6],
     [7,8,9]] ,
    [[1,3,4],
     [2,1,3],
     [5,8,2]]
])
print(c)
print("The shape of the matrix is " ,c.shape)
print("The number of dimension of C array is :", c.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 3 4]
  [2 1 3]
  [5 8 2]]]
The shape of the matrix is  (2, 3, 3)
The number of dimension of C array is : 3


#Reshaping an array

In [ ]:
arr_sample = np.array(range(0,16))
print(arr_sample)
print("dimension",arr_sample.ndim)
print("shape",arr_sample.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
dimension 1
shape (16,)


In [ ]:
arr_sample1=arr_sample.reshape((4,4))
print(arr_sample1)
print("dimension : ",arr_sample1.ndim)
print("shape     : ",arr_sample1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
dimension :  2
shape     :  (4, 4)


**Transpose a matrix( rows to columns)**

In [ ]:
arr2 = arr_sample1.T
print(arr2)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


**Dot product**

In [ ]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [ ]:
i=np.eye(3,3)
print(i)
i.dtype

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


dtype('float64')

**Type conversion :**
U1 - Unicode for a string
int - integer data type

In [ ]:
x=np.array(["2","3","4"])
print(x)
print(x.dtype)
y=x.astype(int)
print(y)
print(y.dtype)


['2' '3' '4']
<U1
[2 3 4]
int64


## 1D Boolean Indexing in NumPy

In [1]:
import numpy as np

# create an array of integers
array1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])

# create a boolean mask using combined logical operators
boolean_mask = (array1 < 10) | (array1 > 40)

# apply the boolean mask to the array
result = array1[boolean_mask]

print(result)

# Output: [ 1  2  4  9 47 51 52]

[ 1  2  4  9 47 51 52]


##2D Boolean indexing in Numpy

In [2]:
import numpy as np

# create a 2D  array
array1 = np.array([[1, 7, 9],
                    [14, 19, 21],
                    [25, 29, 35]])

# create a boolean mask based on the condition
# that elements are greater than 9
boolean_mask = array1 > 9

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)

[14 19 21 25 29 35]
